name: QR Code Generator Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-qr:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install qrcode[pil] cryptography
        
    - name: Run QR Code Generator
      run: python main.py
      
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: qr-code-output
        path: output.png
        retention-days: 30
